spring:
  application:
    name: aneLojae

  datasource:
    url: jdbc:postgresql://postgres_db:5431/loja
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
